app = "next-js-example-winter-2025-eu"
primary_region = "otp"

[mounts]
  source = "postgres"
  destination = "/postgres-volume"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
