export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

export default function AboutPage() {
  return (
    <div>
      <h1>This is my about page</h1>
    </div>
  );
}
