import './globals.scss';
import localFont from 'next/font/local';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const dynamic = 'force-dynamic';

export const metadata = {
  title: {
    default: 'Home page | UpLeveled',
    template: '%s  | UpLeveled',
  },
  description: 'Generated by create next app and a wonderful application',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <div>
            <nav>
              {/* This is not optimized - Use the Next.js Link instead */}
              {/* <a href="/">Home</a> */}

              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/animals">Animals</Link>
              <Link href="/fruits">Fruits</Link>
              <Link href="/contact">Contact</Link>
            </nav>
          </div>
          {Math.floor(Math.random() * 10)}
        </header>
        <main>{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
